### ISSUE TITLE
`yarn test` causes unexpected token import

### ISSUE THREAD

**Issue by Tzikas** [hasura/react-native-auth-boilerplate#8]
```
expo $ yarn test 
yarn test v0.24.6
$ node node_modules/jest/bin/jest.js 
 FAIL  ./App.test.js
  ● Test suite failed to run

    /Users/Squirrel/Documents/Code/NATIVE/EXPO/react-native-auth-boilerplate/expo/node_modules/native-base-shoutem-theme/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle from "./src/connectStyle";
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

    > 1 | import React from 'react';
      2 | import { Root, Container } from 'native-base';
      3 | import { StackNavigator } from 'react-navigation';
      4 | import Index from './Home';
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (node_modules/native-base/dist/src/index.js:1:1115)
      at Object.<anonymous> (App.js:1:770)
```

**Comment by wawhal** [comment]
@Tzikas Tests have not been written yet.
I will be getting to it soon.
Thanks for opening the issue.

If you wish to contribute by writing the test, please let me know.
